<TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0 WIDTH=100%>
	<TR>
		<TD WIDTH=50>&nbsp;

		</TD>

		<TD ALIGN=left CLASS="bodytext">
			<BR><BR>

				<FORM Name = "loginform" METHOD="POST" ACTION="index.php">
					<TABLE ALIGN="left" BORDER=0 CELLSPACING=0 CELLPADDING=4 WIDTH="400" >


						 <TR>
						 <TD VALIGN="top" >
							 Enter your email address here:
						 </TD>
						 <TD VALIGN="top">
							 <INPUT  NAME="email" TYPE="text" SIZE=20>
							 <BR><BR>
						 </TD>
						 </TR>

						 <TR>
						 <TD VALIGN="top" >
							 Enter your password here:
						 </TD>
						 <TD VALIGN="top">
							 <INPUT  NAME="pagespass" TYPE="PASSWORD" SIZE=20>
							 <BR><BR>
						 </TD>
						 </TR>
						 <TR>
						 <TD VALIGN="top" >

						 </TD>
						 <TD VALIGN="top">
							 <INPUT TYPE="SUBMIT" VALUE="Login" name="Login">
						 </TD>
						 </TR>
					 </TABLE>
				</FORM>
			<BR clear="all">

	<BR><BR>
	</TD>
	</TR>
</TABLE>

