<?php
// this is the logout form 
?>
				<FORM Name = "logout" METHOD="POST" ACTION="index.php">
					<TABLE ALIGN="left" BORDER=0 CELLSPACING=0 CELLPADDING=4 WIDTH="400" >
						 <TR>
						 <TD VALIGN="top">
							 <INPUT  NAME="loggingout" TYPE="hidden">
							 <BR><BR>
						 </TD>
						 </TR>
						 <TR>
						 <TD VALIGN="top" >

						 </TD>
						 <TD VALIGN="top">
							 <INPUT TYPE="SUBMIT" VALUE="Logout">
						 </TD>
						 </TR>
					 </TABLE>
				</FORM>


<?php
?>